# -*- coding: utf-8 -*-
"""admission_eligibility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WcofPe2UvCxrbxJVoeINGpb7Wpmj6A_
"""

name = "ali"
age = 19
marks = 79
entry_test = 65
has_certificate = True

if age < 18:
  print("Sorry, you are too young for your admission.")

else:

  if marks >= 80:

    if has_certificate:
     print(f" Hey {name} You are admitted with priority.")
    else:
     print(f" Hey {name} You are admitted")

  elif marks >= 60 and marks < 80:
    if entry_test >= 70:

      if has_certificate:
        print(f"Hey, {name} you are admitted with priority")
      else:
        print(f"Hey {name} you are admitted")

    else:
      print("Sorry, you did not pass the required score entry test.")

  elif marks < 60:
    print("Sorry, your academic marks are very insufficient")

"""we have made a student eligibility program using conditional statements, variables, comparison operators and logical operator

---


"""

