# -*- coding: utf-8 -*-
"""atm_transaction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9lVbygP1715LNyh1UdC3Yg9PXMGPh6Z
"""

#Simple ATM Transaction program
balance = 1000
entered_pin = int(input("Enter pin: "))
pin = 1233
account_active = True

if entered_pin != pin:
   print("Incorrect PIN")
   print("Please try again")

elif not account_active:
 print("You account is inactive")

else:
  transaction_type = input("Transaction type:")

  match transaction_type:

   case "Withdraw" | "withdraw":

    amount = int(input("Withdrawal amount"))

    if amount <= 100:
       print("Your amount must be greater than 100")

    elif amount > balance:
      print("Insufficient balance")

    else:
      print("Withdrawing... Please wait")

      balance -= amount
      print("You successfully withdraw your amount")
      print(f"New current balance is {balance}")

   case "Deposit" | "deposit":

    deposit = int(input("Enter deposit amount:"))

    if deposit < 100:
        print("Minimum deposit is 100")

    elif deposit > 50000:
        print("Maximum deposit is 50000")

    else:
       print("Depositing...Please wait")
       print("You successfully deposited your amount")

       balance += deposit
       print(f"New balance is {balance}")

   case "Balance" | "balance":

     print("Checking balance", end="...")
     print(f"Your balance is {balance}")

   case _:
     print("Incorrect Transaction type. Sorry Try again!")