# -*- coding: utf-8 -*-
"""match_case.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpRWjo8176ipyKsC_lLDm29DVajPO7vz
"""

role = "editor"

match role:
  case "admin":
    print("Full system access")
  case "editor":
    print("Content editing access")
  case "user":
    print("Standard access")
  case "guest":
    print("limited access")
  case "banned":
    print("404! Access denied")
  case _:
    print("Invalid role")