# -*- coding: utf-8 -*-
"""salary_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdXLwffDq9U3Efbd7g6165D4VwCoBY3Y
"""

#salary calculator
employe = "Zoha Javaid"
montly_salary = 50000
overtime_hours = 8
hourly_rate = 500
bonus = 7500
tax_rate =  10
insurance = 2000

overtime_pay = overtime_hours * hourly_rate

gross_salary = montly_salary + overtime_pay + bonus

tax = gross_salary * tax_rate / 100

net_salary = gross_salary - tax - insurance

print("-" * 20)
print("Employee", employe)
print("-" * 20)
print("Overtime Hours:", overtime_hours)
print("Overtime pay", overtime_pay)
print("Gross Salary:", gross_salary)
print("Bonus:", bonus)
print("Tax Cut:", tax)
print("Insurance cut:", insurance)
print("Net Salary:", net_salary)
print("-" * 20)

import sys
print(sys.version)

"""i'm actually going to make a mini project where I'm gonna calculate the salary, you know"""