# -*- coding: utf-8 -*-
"""variables_built_in_types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10oo3qsZckORRacjibFesUnU7SGGeRGR4

actually, we are going to learn variables built-in types type conversion in this chapter
"""

#practice 1
name = "Ali" # variable name refers to a string object
age = 20 #variable age refers to an integer object
height = 1.20
is_student = True #boolean value
nothing = None #absence of value
print(name) #display the value of name on the screen
print(type(name)) #type() checks object type
print(age)
print(type(age))
print(height)
print(type(height))
print(is_student)
print(type(is_student))
print(nothing)
print(type(nothing))


#practice 2: all built-in-types

#numerical types
age = 20 #int (immutable)
print(type(age))
height = 2.2 #float (immutable)
print(type(height))
Physics = 1.3j #complex (immutable)
print(type(Physics))

has_id = False #boolean (immutable)

#sequence type
fruits = ["apple", "mango"] #list (mutable)
print(type(fruits))
numbers = (1,2,3) #tuple (immutable)
print(type(numbers))
checking_range = (5) #range (immutable)
print(type(checking_range))

#set types
students = {"ali", "ahmed"} #set (mutable)
print(type(students))

dictionaries = {"name": "ali", "name2": "umar"} #dict (mutable)
print(type(dictionaries))

nothing_spec = None #NoneType (immutable)
print(type(nothing_spec))

name = "ali" #str (immutable)
print(type(name))

#binary types
image = b"zoha" #bytes (immutable)
print(type(image))

#practice 3:  variable scan refer to objects of different types
name = "Ahmed"
age = 22
height = 1.27
is_student = False
nothing = None

print(name)
print(age)
print(height)
print(is_student)
print(nothing)

#practice 4: changing variables types
age = float(age)
print(type(age))

age = str(age)
print(type(age))

age = complex(age)
print(type(age))

height = int(height)
print(type(height))

is_student = int(is_student)
print(type(is_student))

numbers = tuple[1,2,3]
print(type(numbers))

fruits = ("apple", "mango")
fruits1 = list(fruits)
print(type(fruits1))

names = ("dock", "microwave")
names1 = set(names)
print(type(names1))

dictionaries = dict["ali", "umar"]
print(type(dictionaries))

#practice 5: rebinding/ressingment
x = 20
y = x #y refering to same object as x
x = 30 #x has been rebound
print(x)
print(y)

