# -*- coding: utf-8 -*-
"""Weekly_salary_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XvuT0Vl5lJyI_y5UbKpnFUCziB2cbqGe
"""



#practice 3: employer weekly salary calculator program
employer = "Zoha Altaf"
hourly_rate = int(input("Enter your hourly rate: "))
hours_worked = int(input("Enter your hours worked: "))
overtime_rate = int(input("Enter your overtime rate: "))
tax_rate = 0.20

normal_hours = 40

# Calculate overtime hours (will be 0 if hours_worked <= normal_hours)
overtime_hours = max(0, hours_worked - normal_hours)

normal_pay = hourly_rate * normal_hours

overtime_rate_pay = overtime_rate
overtime_hourly_rate = hourly_rate + overtime_rate
overtime_pay = overtime_hourly_rate * overtime_hours

gross_pay = normal_pay + overtime_pay
tax_amount = tax_rate * gross_pay
net_salary = gross_pay - tax_amount

print("-" * 10)
print("Employer:", employer)
print("Normal pay:", normal_pay)
print("Overtime hours:", overtime_hours)
print("Overtime hourly rate:", overtime_rate_pay)
print("Overtime pay:", overtime_pay)
print("Gross pay:", gross_pay)
print(f"Tax amount: {tax_amount:.2f}")
print("Total salary:", net_salary)